services:
  - type: web
    name: ai-receptionist
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app

    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: receptionist-db
          property: connectionString
      - key: FLASK_ENV
        value: production
      - key: FLASK_APP
        value: app.py
      - key: APP_ENC_KEY
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: TWILIO_ACCOUNT_SID
        sync: false
      - key: TWILIO_AUTH_TOKEN
        sync: false
      - key: TWILIO_PHONE_NUMBER
        sync: false
      - key: SECRET_KEY
        sync: false
      - key: INIT_ADMIN_EMAIL
        value: admin@example.com
      - key: INIT_ADMIN_USERNAME
        value: admin
      - key: INIT_ADMIN_PASSWORD
        value: StrongP@ssw0rd!

    preDeployCommand: |
      flask db upgrade
      flask db seed_demo
