services:
  - type: web
    name: ai-receptionist
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: receptionist-db
          property: connectionString
      - key: SECRET_KEY
        sync: false
      - key: APP_ENC_KEY
        sync: false
      - key: TWILIO_ACCOUNT_SID
        sync: false
      - key: TWILIO_AUTH_TOKEN
        sync: false
      - key: TWILIO_PHONE_NUMBER
        sync: false
    preDeployCommand: flask db upgrade
databases:
  - name: receptionist-db
    plan: free
